name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add sphinx-action@master action per API
      - name: Build Data API doc
        id: build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "exabel/api/data"
      # Will deploy all targets listed in firebase.json
      - name: Deploy all API docs to Firebase
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXABEL_DOC }}'
          channelId: live
          projectId: exabel-doc
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Post to Slack
        uses: hkusu/slack-post-action@v1
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
        with:
          channel: '#prod-environment'
          message: 'Deployed doc: ${{ steps.deploy.outputs.urls }}'
